"""Slack Block Kit report builder + renderers.

Produces real Block Kit JSON (postable to a webhook) and a text/markdown preview
the UI renders inline — so the demo works with or without a Slack workspace.
"""
from __future__ import annotations

import json

import httpx

from .config import get_settings


def build_daily_brief(payload: dict) -> list[dict]:
    """payload keys: date, headline, flagship, kpis[], competitor_moves[], inventory_risks[], action"""
    blocks: list[dict] = [
        {"type": "header", "text": {"type": "plain_text", "text": f"🥋 Ronin Athletics — Daily Amazon Brief"}},
        {"type": "context", "elements": [{"type": "mrkdwn", "text": f"*{payload.get('date','')}*  ·  auto-generated by the agent fleet"}]},
        {"type": "section", "text": {"type": "mrkdwn", "text": f"*{payload.get('headline','')}*"}},
        {"type": "divider"},
    ]
    kpis = payload.get("kpis", [])
    if kpis:
        blocks.append({"type": "section", "fields": [{"type": "mrkdwn", "text": k} for k in kpis[:8]]})
    moves = payload.get("competitor_moves", [])
    if moves:
        blocks.append({"type": "section", "text": {"type": "mrkdwn",
            "text": "*Competitor moves*\n" + "\n".join(f"• {m}" for m in moves)}})
    risks = payload.get("inventory_risks", [])
    if risks:
        blocks.append({"type": "section", "text": {"type": "mrkdwn",
            "text": "*Inventory risks*\n" + "\n".join(f"• {r}" for r in risks)}})
    if payload.get("action"):
        blocks.append({"type": "divider"})
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": f"*✅ Recommended action*\n{payload['action']}"}})
    return blocks


def render_text(blocks: list[dict]) -> str:
    """Flatten Block Kit to markdown for inline preview."""
    lines: list[str] = []
    for b in blocks:
        t = b.get("type")
        if t == "header":
            lines.append(f"### {b['text']['text']}")
        elif t == "context":
            lines.append("_" + " ".join(e["text"] for e in b["elements"]) + "_")
        elif t == "divider":
            lines.append("\n---")
        elif t == "section":
            if "text" in b:
                lines.append(b["text"]["text"])
            if "fields" in b:
                lines.append("\n".join(f["text"] for f in b["fields"]))
    return "\n\n".join(lines)


def post_to_slack(blocks: list[dict]) -> bool:
    url = get_settings().slack_webhook_url
    if not url:
        return False
    try:
        r = httpx.post(url, json={"blocks": blocks}, timeout=10)
        return r.status_code == 200
    except Exception:  # noqa: BLE001
        return False


def to_json(blocks: list[dict]) -> str:
    return json.dumps({"blocks": blocks}, indent=2)
